services:
  file:
    container_name: file
    env_file:
      - .env
#    build:
#      context: .
#      dockerfile: Dockerfile-local
    image: pince:v1
    restart: unless-stopped
    depends_on:
      - file-postgres
    environment:
      SERVICE_NAME: file
      DB_HOST: file-postgres
      DB_NAME: file
      DB_USERNAME: ${DB_USERNAME:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./:/app
    ports:
      - 5012:8080
      - 45012:40000
    networks:
      - file-network
      - file-postgres-network

  file-postgres:
    container_name: ${DB_HOST:-file-postgres}
    image: postgres:alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: file
    ports:
      - 54326:5432
    networks:
      - file-postgres-network

  adminer:
    container_name: adminer-postgres
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - file-postgres
    networks:
      - file-postgres-network


networks:
  file-network:
    name: file-network
    driver: bridge
  file-postgres-network:
    name: file-postgres-network
    driver: bridge