services:
  file:
    container_name: file
    env_file:
      - .env
    image: ${DOCKERHUB_USERNAME:-pthaiit210501}/pince-dev:v1
    pull_policy: always
    restart: unless-stopped
    volumes:
      - file-data:/app/storage
    depends_on:
      - file-postgres
    environment:
      SERVICE_NAME: file
      DB_HOST: file-postgres
      DB_NAME: file
      DB_USERNAME: ${DB_USERNAME:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - 5006:8080
    networks:
      - file-network
      - file-postgres-network

  file-postgres:
    container_name: ${DB_HOST:-file-postgres}
    image: postgres:alpine3.19
    restart: unless-stopped
    volumes:
      - file-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: file
    ports:
      - 54326:5432
    networks:
      - file-postgres-network

  adminer:
    container_name: adminer-postgres
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - file-postgres
    networks:
      - file-postgres-network


networks:
  file-postgres-network:
    name: file-postgres-network
    driver: bridge
  file-network:
    name: file-network
    driver: bridge


volumes:
  file-postgres-data:
    name: file-postgres-data
  file-data:
    name: file-data