name: Deploy app [dev]
run-name: Deploy app for development environment
on:
  workflow_run:
    workflows: [Dockerize app]
    types: [completed]

jobs:
  Build-image:
    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: development
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          set -x
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.MY_VPS_IP_ADDRESS }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.MY_VPS_USER }}@${{ secrets.MY_VPS_IP_ADDRESS }} << 'EOF'
            set -x
            cd ${{ secrets.COMMON_SETUP_REPOSITORY_PATH }}
            chmod +x ./create_network.sh
            sudo ./create_network.sh
          
            cd ${{ secrets.REPOSITORY_PATH }}
            git checkout development
            git pull
          
            sudo DB_USERNAME=${{ secrets.APP_DB_USERNAME }} DB_PASSWORD=${{ secrets.APP_DB_PASSWORD }} docker compose -f compose-development.yaml up -d
          EOF