name: Dockerize app
run-name: Dockerize action
on:
  push:
    branches:
      - development

jobs:
  Build-image:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-development
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/pince:dev-v1